<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>rp.spark</RootNamespace>
    <AssemblyName>SPARK</AssemblyName>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <OutputPath>bin\$(Platform)\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <AllowedReferenceRelatedFileExtensions>.none</AllowedReferenceRelatedFileExtensions>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlishHUD" Version="1.3.0" ExcludeAssets="runtime;contentFiles;analyzers" />
    <PackageReference Include="System.ComponentModel.Composition" Version="6.0.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.8" ExcludeAssets="runtime" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" ExcludeAssets="runtime" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" ExcludeAssets="runtime" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <Target Name="ForceRestore"
          BeforeTargets="CollectPackageReferences;ResolvePackageAssets"
          Condition="!Exists('$(BaseIntermediateOutputPath)project.assets.json') AND '$(ForceRestoreRunning)' != 'true'">
    <Exec Command="dotnet restore &quot;$(MSBuildProjectFullPath)&quot; -p:ForceRestoreRunning=true" />
  </Target>
</Project>
